name: ci-checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (for linters)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTMLHint
        run: htmlhint "/*.html"

      - name: Install Stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Create Stylelint config
        run: |
          echo "module.exports = { extends: 'stylelint-config-standard' };" > .stylelintrc.cjs

      - name: Run Stylelint
        run: stylelint "/*.css"